apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmsnesia.fullname" . }}
  labels:
    {{- include "cmsnesia.labels" . | nindent 4 }}
data:
  spring.application.json: 'eyJzcHJpbmcuYXBwbGljYXRpb24ubmFtZSI6ImNtc25lc2lhIiwic3ByaW5nLmRhdGEubW9uZ29kYi51cmkiOiJtb25nb2RiOi8vYXJkaWthcnM6YWJjMTIzQGRzMTE3ODA2Lm1sYWIuY29tOjE3ODA2L2hlcm9rdV8xbmo0a2txYz9yZXRyeVdyaXRlcz1mYWxzZSIsImdpdGh1Yi5vd25lciI6ImNtc25lc2lhIiwiZ2l0aHViLnJlcG8iOiJhc3NldHMiLCJnaXRodWIuYWNjZXNzVG9rZW4iOiJzZWNyZXQiLCJjbXNuZXNpYS50b2tlbi5pc3N1ZXIiOiJhcmRpa2FycyIsImNtc25lc2lhLnRva2VuLmFjY2Vzc1Rva2VuRXhwYXJhdGlvbiI6IjIwNzM2MDAwMCIsImNtc25lc2lhLnRva2VuLnJlZnJlc2hUb2tlbkV4cGFyYXRpb24iOiI0MTQ3MjAwMDAiLCJjbXNuZXNpYS50b2tlbi5zZWNyZXQiOiI0N3VEeEU3NCIsImNtc25lc2lhLnRva2VuLm1heCI6IjAiLCJzcHJpbmcuY2xvdWQubG9hZGJhbGFuY2VyLnJpYmJvbi5lbmFibGVkIjogImZhbHNlIn0='