version: '3'

services:
  mongodb:
    image: mongo:4.0.12
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ardikars
      MONGO_INITDB_ROOT_PASSWORD: 123456

  influxdb:
    image: influxdb:1.7.6
    ports:
      - 8086:8086
    volumes:
      - /var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: ardikars
      INFLUXDB_USER: ardikars
      INFLUXDB_USER_PASSWORD: 123456
      INFLUXDB_ADMIN_USER: ardikars
      INFLUXDB_ADMIN_PASSWORD: 123456