apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "cmsnesia-ingress"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - "api.cmsnesia.com"
      secretName: cmsnesia-tls
  rules:
    - host: "api.cmsnesia.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: "cmsnesia-service"
              servicePort: 8080