on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@master

      - name: Build container image
        run: docker build -t ardikars/cmsnesia:latest .

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push image to Docker Hub
        run: docker push ardikars/cmsnesia

      - name: Create deployment configuration
        run: |
          echo "${{ secrets.k8s_digital_ocean_config }}" | base64 --decode > .kubeconfig
          echo "${{ secrets.k8s_deployment_base64 }}" | base64 --decode > .k8s/templates/deployment.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          kubectl --kubeconfig=.kubeconfig apply -f .k8s/templates/namespace.yaml
          kubectl --kubeconfig=.kubeconfig apply -f .k8s/templates/deployment.yaml
          kubectl --kubeconfig=.kubeconfig apply -f .k8s/templates/service.yaml

      - name: Verify deployment
        run: kubectl --kubeconfig=.kubeconfig rollout status deployment/cmsnesia-web

      - name: Caching
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-