name: 'Heroku deployment'

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: 'Heroku deployment'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
#      - name: build
#        run: |
#          docker build -t ardikars/gri-web:latest .
#          docker image tag ardikars/gri-web:latest registry.heroku.com/gri-web/web:latest
#          docker images
#      - name: login
#        run: |
#          docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
#      - name: push
#        run: |
#          docker push registry.heroku.com/gri-web/web